CREATE TABLE restaurant_info (
    id INT AUTO_INCREMENT PRIMARY KEY,
    SIGUN_NM VARCHAR(50),
    SIGUN_CD VARCHAR(10),
    RESTRT_NM VARCHAR(100),
    REPRSNT_FOOD_NM VARCHAR(100),
    TASTFDPLC_TELNO VARCHAR(20),
    RM_MATR TEXT,
    REFINE_LOTNO_ADDR VARCHAR(200),
    REFINE_ROADNM_ADDR VARCHAR(200),
    REFINE_ZIP_CD VARCHAR(10),
    REFINE_WGS84_LOGT DOUBLE,
    REFINE_WGS84_LAT DOUBLE
);
CREATE TABLE user (
    userId BIGINT AUTO_INCREMENT PRIMARY KEY,
    loginId VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    createdDate varchar(100)
);